### ISSUE TITLE
SELinux breaks this

### ISSUE THREAD

**Issue by josegonzalez** [rvanlaar/dokku-nginx-stream#2]
Rather than including an nginx conf from the app directory, would be better to have an `include /etc/nginx/app-stream/*.conf;` directive. The filenames would be `$APP.conf`.

I think the way dokku core has done it is definitely not correct, and we'll be fixing it in the future, but better for you to fix this now than deal with it later.

Note: writing to the `/etc/nginx` path may require a sudoers entry, not sure.

**Comment by rvanlaar** [comment]
Made a branch to track these changes: https://github.com/rvanlaar/dokku-nginx-stream/tree/conf-location

**Comment by rvanlaar** [comment]
Thank you for the feedback. I've incorporated it in the project.
