### ISSUE TITLE
no port in upstream

### ISSUE THREAD

**Issue by olamide203** [rvanlaar/dokku-nginx-stream#5]
Hi, i keep getting this `nginx` error

```
nginx: [emerg] no port in upstream "byke-tcp-3000" in /etc/nginx/app-stream/byke.conf:4
nginx: configuration file /etc/nginx/nginx.conf test failed
```
and when I checked inside the  `/etc/nginx/app-stream/byke.conf` file i got this
```
server {
    listen     3000;
    proxy_pass byke-tcp-3000;
}
```

I know that there is a maintained version at [josegonzalez](https://github.com/josegonzalez)/[dokku-nginx-stream](https://github.com/josegonzalez/dokku-nginx-stream) but unfortunately, Issues are blocked there

**Comment by rvanlaar** [comment]
Nice to hear from you and to see you have the same problem I once had. Getting a TCP port exposed through nginx.

Try to contact the Dokku team via their socials. Their site mentions: IRC, Discord and Github Discussions as possible options.

**Comment by olamide203** [comment]
Thank you, I later reached  out to dokku team on their discord chanel. it turns out this plugin only works on dokku versions `0.25.0+` got it to work after updating dokku to the latest  version. I think This should be added to the documentation

**Comment by rvanlaar** [comment]
Nice to hear it got resolved.
Josegonzalez did add it in the documentation. 
Closing this ticket.
